version: '3'
services:
  chatgpt:
    image: pojono/chatgpt:${DOCKER_TAG}
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    restart: always